[General]
font_family=DejaVu Sans Mono
font_size=11
theme=light

[blame]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x11\0\0\x1\\\0\0\0\xc7\0\0\x6\xaf\0\0\x3\xcc\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\x1d\0\0\a\x7f\0\0\x4\x11)

[browse]
col_width_author=262
col_width_date=100
col_width_stats=57
diff_tab_index=0
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x11\0\0\0\xe7\0\0\0\x92\0\0\x6\xdc\0\0\x3\xc4\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\x1d\0\0\a\x7f\0\0\x4\x11)
isMaximized=true
show_author=true
show_date=true
show_stats=true
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xda\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[main]
col_width_author=120
col_width_date=100
col_width_stats=80
diff_tab_index=1
isMaximized=false
show_author=true
show_date=true
show_multiselect_options=true
show_rebase_options=false
show_stats=true
show_tags=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xda\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[startup]
auto_check_updates=false
